### ISSUE TITLE
Void Upgrade eats all my items

### ISSUE THREAD

**Issue by dqflynn** [djohn49/sgc_issue_tracker#1]
The void upgrade from Storage Drawers doesn't just eat excess items, but instead decides to just drop my drawer storage to zero until something else is inputted. Sometimes, for unknown reasons, I can get the items back, but I don't know how to replicate it.

**Comment by djohn49** [comment]
This seems like a bug in storage drawers, and there's some relevant talk of it on the issue tracker:
https://github.com/jaquadro/StorageDrawers/issues/869 (not quite the same)
https://github.com/jaquadro/StorageDrawers/issues/811 (old)
https://github.com/jaquadro/StorageDrawers/issues/930 (old)

Looking into these issues to find a workaround or report the information that we have would be the way to move forward here. As it seems to be an upstream mod bug and not an issue in the pack that I can fix at the pack level, I'm closing this issue. If you discover a pack change that would fix it (e.g. configuration change or update a mod) please re-open this issue.
